"""initial schema

Revision ID: bec852712a4a
Revises: 
Create Date: 2026-07-29 00:29:03.492508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bec852712a4a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ix_works_title_trgm is a gin_trgm_ops index, so pg_trgm must exist before the
    # tables are created. db/init/10_provenance.sql does this for a fresh container,
    # but a migration has to stand on its own against any empty database.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gin")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('works_count', sa.Integer(), nullable=False),
    sa.Column('cited_by_count', sa.BigInteger(), nullable=False),
    sa.Column('orcid', sa.Text(), nullable=True),
    sa.Column('corpus_degree', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_corpus_degree'), 'authors', ['corpus_degree'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('src', sa.String(length=32), nullable=False),
    sa.Column('dst', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('context', sa.String(length=32), nullable=False),
    sa.Column('relation', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('src', 'dst', 'context', name='uq_graph_edge')
    )
    op.create_index(op.f('ix_graph_edges_context'), 'graph_edges', ['context'], unique=False)
    op.create_index(op.f('ix_graph_edges_dst'), 'graph_edges', ['dst'], unique=False)
    op.create_index(op.f('ix_graph_edges_relation'), 'graph_edges', ['relation'], unique=False)
    op.create_index(op.f('ix_graph_edges_src'), 'graph_edges', ['src'], unique=False)
    op.create_table('institutions',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('ror', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=8), nullable=True),
    sa.Column('corpus_degree', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institutions_corpus_degree'), 'institutions', ['corpus_degree'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('warmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_token'), 'profiles', ['token'], unique=True)
    op.create_table('topics',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('subfield', sa.Text(), nullable=True),
    sa.Column('field', sa.Text(), nullable=True),
    sa.Column('domain', sa.Text(), nullable=True),
    sa.Column('corpus_degree', sa.Integer(), nullable=False),
    sa.Column('idf', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_corpus_degree'), 'topics', ['corpus_degree'], unique=False)
    op.create_table('venues',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=True),
    sa.Column('issn_l', sa.String(length=16), nullable=True),
    sa.Column('publisher', sa.Text(), nullable=True),
    sa.Column('corpus_degree', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_corpus_degree'), 'venues', ['corpus_degree'], unique=False)
    op.create_table('works',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('year', sa.SmallInteger(), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('cited_by_count', sa.Integer(), nullable=False),
    sa.Column('doi', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=48), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('is_oa', sa.Boolean(), nullable=False),
    sa.Column('is_stub', sa.Boolean(), nullable=False),
    sa.Column('venue_id', sa.String(length=24), nullable=True),
    sa.Column('ref_count', sa.Integer(), nullable=False),
    sa.Column('in_corpus_cited_by', sa.Integer(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_cited_by_count'), 'works', ['cited_by_count'], unique=False)
    op.create_index(op.f('ix_works_in_corpus_cited_by'), 'works', ['in_corpus_cited_by'], unique=False)
    op.create_index(op.f('ix_works_is_stub'), 'works', ['is_stub'], unique=False)
    op.create_index('ix_works_title_trgm', 'works', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_index('ix_works_tsv', 'works', ['tsv'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_works_venue_id'), 'works', ['venue_id'], unique=False)
    op.create_index(op.f('ix_works_year'), 'works', ['year'], unique=False)
    op.create_table('citations',
    sa.Column('src_id', sa.String(length=24), nullable=False),
    sa.Column('dst_id', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['dst_id'], ['works.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['src_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('src_id', 'dst_id')
    )
    op.create_index('ix_citations_dst', 'citations', ['dst_id'], unique=False)
    op.create_table('read_marks',
    sa.Column('profile_id', sa.String(length=40), nullable=False),
    sa.Column('work_id', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'work_id')
    )
    op.create_table('trust',
    sa.Column('profile_id', sa.String(length=40), nullable=False),
    sa.Column('work_id', sa.String(length=24), nullable=False),
    sa.Column('strength', sa.SmallInteger(), nullable=False),
    sa.Column('is_distrust', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'work_id')
    )
    op.create_table('work_authors',
    sa.Column('work_id', sa.String(length=24), nullable=False),
    sa.Column('author_id', sa.String(length=24), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id', 'author_id')
    )
    op.create_table('work_institutions',
    sa.Column('work_id', sa.String(length=24), nullable=False),
    sa.Column('institution_id', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id', 'institution_id')
    )
    op.create_table('work_topics',
    sa.Column('work_id', sa.String(length=24), nullable=False),
    sa.Column('topic_id', sa.String(length=24), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_id', 'topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_topics')
    op.drop_table('work_institutions')
    op.drop_table('work_authors')
    op.drop_table('trust')
    op.drop_table('read_marks')
    op.drop_index('ix_citations_dst', table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_works_year'), table_name='works')
    op.drop_index(op.f('ix_works_venue_id'), table_name='works')
    op.drop_index('ix_works_tsv', table_name='works', postgresql_using='gin')
    op.drop_index('ix_works_title_trgm', table_name='works', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_works_is_stub'), table_name='works')
    op.drop_index(op.f('ix_works_in_corpus_cited_by'), table_name='works')
    op.drop_index(op.f('ix_works_cited_by_count'), table_name='works')
    op.drop_table('works')
    op.drop_index(op.f('ix_venues_corpus_degree'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_topics_corpus_degree'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_profiles_token'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_institutions_corpus_degree'), table_name='institutions')
    op.drop_table('institutions')
    op.drop_index(op.f('ix_graph_edges_src'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_relation'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_dst'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_context'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_authors_corpus_degree'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
