"""Upload confirm: Postgres-first, engine reconciled (spec B7/B3-method).

Source-of-truth invariant (the same one bootstrap.py enforces): Postgres
relational tables are the truth; graph_edges is a derived materialisation; the
engine is a cache of graph_edges. Confirm writes down the stack in that order:

  1. ONE Postgres transaction: works (+ entity rows) for the paper and its
     OpenAlex-resolvable references, citations, graph_edges (edge parity with
     scripts/build_graph.py), trust + trust_sources, graph_meta.version bump,
     upload.status='applying'.
  2. After commit: ONE mr_put_edges batch (non-clearing, idempotent) pushing
     exactly the rows just written, plus the profile's new trust edges.
  3. Engine success -> status='confirmed'. Engine failure -> the committed
     truth stays, status='engine_pending'; the background sweep retries, and a
     restart repairs for free because bootstrap.push_graph_to_engine() reloads
     ALL of graph_edges.

Edge parity, mirrored from scripts/build_graph.py (NOT approximated): `cites`
1.00 x epoch_factor(cited year) and `cited_by` 0.15 x the same factor;
entity edges (authored_by/wrote, tagged/tags, published_in/publishes,
affiliated/hosts) only where OpenAlex metadata exists, hub-damped by
1/sqrt(corpus_degree) and IDF-scaled for topics. UL... local works get no
entity edges: there is no reliable metadata to derive them from.

Coupling/co-citation edges are NOT written here -- they are regenerated by the
next full rebuild (spec, out of scope), which the survival gate verifies.
"""
from __future__ import annotations

import logging
import math
import threading
import time

from sqlalchemy import text
from sqlalchemy.orm import Session

from . import config, ranking, services
from .graphmeta import bump_graph_version
from .meritrank import Edge, MeritRank
from .models import (
    Trust, TrustSource, Upload, UploadReference, Work,
    profile_node, work_node,
)
from .openalex import OpenAlex, OpenAlexUnavailable, short_id

log = logging.getLogger("provenance.confirm")

W = config.DEFAULT_WEIGHTS
# Confirm cap (spec): more accepted references than this is rejected with a
# specific reason, whichever engine path is in use.
MAX_CONFIRM_REFERENCES = 200


class ConfirmError(Exception):
    """User-facing rejection with a specific reason."""


def epoch_factor(year: int | None,
                 half_life: float = config.DEFAULT_EPOCH_HALF_LIFE_YEARS) -> float:
    """Byte-for-byte the build_graph.py formula. Applied to the CITED work's
    year, exactly as the rebuild does."""
    if not year or half_life <= 0:
        return 1.0
    age = max(0, config.EPOCH_REFERENCE_YEAR - year)
    return max(0.4, 0.5 ** (age / half_life))


def damp(degree: int) -> float:
    return 1.0 / math.sqrt(max(degree, 1))


# ---------------------------------------------------------------------------
# OpenAlex work materialisation
# ---------------------------------------------------------------------------

def _reconstruct_abstract(inv: dict | None) -> str | None:
    if not inv:
        return None
    positions = [(i, w) for w, idxs in inv.items() for i in idxs]
    if not positions:
        return None
    positions.sort()
    return " ".join(w for _, w in positions)[:8000]


def materialise_openalex_work(db: Session, oa: OpenAlex, oa_id: str) -> str | None:
    """Create a full corpus works row (+ entity rows and links) from OpenAlex.
    Ordinary corpus record: source='openalex' (spec Visibility: only UL...
    locals are labelled). Returns the work id, or None if OpenAlex cannot
    supply the record right now."""
    existing = db.get(Work, oa_id)
    if existing is not None:
        return oa_id
    try:
        w = oa.get(f"works/{oa_id}")
    except OpenAlexUnavailable:
        return None
    if not w:
        return None

    venue_id = None
    loc = (w.get("primary_location") or {}).get("source") or {}
    if loc.get("id"):
        venue_id = short_id(loc["id"])
        db.execute(text(
            "INSERT INTO venues (id, display_name, type, issn_l, publisher, corpus_degree) "
            "VALUES (:i, :n, :t, :issn, :p, 0) ON CONFLICT (id) DO NOTHING"),
            {"i": venue_id, "n": loc.get("display_name"),
             "t": (loc.get("type") or "")[:32] or None,
             "issn": (loc.get("issn_l") or "")[:16] or None,
             "p": loc.get("host_organization_name")})

    db.execute(text(
        "INSERT INTO works (id, title, abstract, year, publication_date, "
        " cited_by_count, doi, type, language, is_oa, is_stub, venue_id, "
        " ref_count, in_corpus_cited_by, source) "
        "VALUES (:id, :title, :abstract, :year, CAST(:pdate AS date), :cited, :doi, :type, "
        " :lang, :oa, false, :venue, 0, 0, 'openalex') "
        "ON CONFLICT (id) DO NOTHING"),
        {"id": oa_id, "title": w.get("title") or w.get("display_name"),
         "abstract": _reconstruct_abstract(w.get("abstract_inverted_index")),
         "year": w.get("publication_year"),
         "pdate": w.get("publication_date"),
         "cited": int(w.get("cited_by_count") or 0),
         "doi": w.get("doi"), "type": (w.get("type") or "")[:48] or None,
         "lang": (w.get("language") or "")[:8] or None,
         "oa": bool((w.get("open_access") or {}).get("is_oa")),
         "venue": venue_id})

    for pos, auth in enumerate(w.get("authorships") or []):
        a = auth.get("author") or {}
        aid = short_id(a.get("id"))
        if not aid:
            continue
        db.execute(text(
            "INSERT INTO authors (id, display_name, works_count, cited_by_count, "
            " orcid, corpus_degree) VALUES (:i, :n, 0, 0, :o, 0) "
            "ON CONFLICT (id) DO NOTHING"),
            {"i": aid, "n": a.get("display_name"), "o": a.get("orcid")})
        db.execute(text(
            "INSERT INTO work_authors (work_id, author_id, position) "
            "VALUES (:w, :a, :p) ON CONFLICT DO NOTHING"),
            {"w": oa_id, "a": aid, "p": pos})
        db.execute(text(
            "UPDATE authors SET corpus_degree = corpus_degree + 1 WHERE id = :a"),
            {"a": aid})
        for inst in auth.get("institutions") or []:
            iid = short_id(inst.get("id"))
            if not iid:
                continue
            db.execute(text(
                "INSERT INTO institutions (id, display_name, ror, country_code, "
                " corpus_degree) VALUES (:i, :n, :r, :c, 0) "
                "ON CONFLICT (id) DO NOTHING"),
                {"i": iid, "n": inst.get("display_name"), "r": inst.get("ror"),
                 "c": (inst.get("country_code") or "")[:8] or None})
            db.execute(text(
                "INSERT INTO work_institutions (work_id, institution_id) "
                "VALUES (:w, :i) ON CONFLICT DO NOTHING"), {"w": oa_id, "i": iid})
            db.execute(text(
                "UPDATE institutions SET corpus_degree = corpus_degree + 1 "
                "WHERE id = :i"), {"i": iid})

    for t in w.get("topics") or []:
        tid = short_id(t.get("id"))
        if not tid:
            continue
        db.execute(text(
            "INSERT INTO topics (id, display_name, subfield, field, domain, "
            " corpus_degree, idf) VALUES (:i, :n, :s, :f, :d, 0, 1.0) "
            "ON CONFLICT (id) DO NOTHING"),
            {"i": tid, "n": t.get("display_name"),
             "s": (t.get("subfield") or {}).get("display_name"),
             "f": (t.get("field") or {}).get("display_name"),
             "d": (t.get("domain") or {}).get("display_name")})
        db.execute(text(
            "INSERT INTO work_topics (work_id, topic_id, score) "
            "VALUES (:w, :t, :s) ON CONFLICT DO NOTHING"),
            {"w": oa_id, "t": tid, "s": float(t.get("score") or 0.0)})
        db.execute(text(
            "UPDATE topics SET corpus_degree = corpus_degree + 1 WHERE id = :t"),
            {"t": tid})

    return oa_id


def _local_work(db: Session, title: str | None) -> str:
    """A UL... local work: content that exists solely because a user uploaded
    it. Ids come from work_local_id_seq and are NEVER reused (spec B6: the
    engine has no transactional memory; a reused id would inherit phantom
    edges from an abandoned confirm)."""
    n = db.execute(text("SELECT nextval('work_local_id_seq')")).scalar_one()
    wid = f"L{n}"
    db.execute(text(
        "INSERT INTO works (id, title, cited_by_count, is_oa, is_stub, "
        " ref_count, in_corpus_cited_by, source) "
        "VALUES (:id, :title, 0, false, false, 0, 0, 'user_upload')"),
        {"id": wid, "title": title or "(untitled upload)"})
    return wid


# ---------------------------------------------------------------------------
# Edge derivation (parity with scripts/build_graph.py)
# ---------------------------------------------------------------------------

def _entity_edges_for(db: Session, wid: str) -> list[Edge]:
    """Entity edges for one work, exactly as build_graph.py derives them."""
    edges: list[Edge] = []
    wn = work_node(wid)
    for aid, deg in db.execute(text(
        "SELECT wa.author_id, a.corpus_degree FROM work_authors wa "
        "JOIN authors a ON a.id = wa.author_id WHERE wa.work_id = :w"),
            {"w": wid}).all():
        an = f"BA{aid[1:]}" if aid.startswith("A") else f"BA{aid}"
        edges.append(Edge(wn, an, W["authored_by"], "author", "authored_by"))
        edges.append(Edge(an, wn, W["wrote"] * damp(deg), "author", "wrote"))
    max_idf = db.execute(text(
        "SELECT coalesce(max(idf), 1.0) FROM topics")).scalar_one() or 1.0
    for tid, deg, idf in db.execute(text(
        "SELECT wt.topic_id, t.corpus_degree, t.idf FROM work_topics wt "
        "JOIN topics t ON t.id = wt.topic_id WHERE wt.work_id = :w"),
            {"w": wid}).all():
        tn = f"BT{tid[1:]}" if tid.startswith("T") else f"BT{tid}"
        scale = (idf or 0.0) / max_idf
        edges.append(Edge(wn, tn, W["tagged"] * scale, "topic", "tagged"))
        edges.append(Edge(tn, wn, W["tags"] * scale * damp(deg), "topic", "tags"))
    row = db.execute(text(
        "SELECT w.venue_id, v.corpus_degree FROM works w "
        "JOIN venues v ON v.id = w.venue_id "
        "WHERE w.id = :w AND w.venue_id IS NOT NULL"), {"w": wid}).first()
    if row:
        vid, deg = row
        vn = f"BS{vid[1:]}" if vid.startswith("S") else f"BS{vid}"
        edges.append(Edge(wn, vn, W["published_in"], "venue", "published_in"))
        edges.append(Edge(vn, wn, W["publishes"] * damp(deg), "venue", "publishes"))
    for iid, deg in db.execute(text(
        "SELECT wi.institution_id, i.corpus_degree FROM work_institutions wi "
        "JOIN institutions i ON i.id = wi.institution_id WHERE wi.work_id = :w"),
            {"w": wid}).all():
        inn = f"BI{iid[1:]}" if iid.startswith("I") else f"BI{iid}"
        edges.append(Edge(wn, inn, W["affiliated"], "institution", "affiliated"))
        edges.append(Edge(inn, wn, W["hosts"] * damp(deg), "institution", "hosts"))
    return edges


def _persist_edges(db: Session, edges: list[Edge]) -> None:
    """Max-weight-wins on (src, dst, context) collisions -- the same rule
    build_graph.dedupe() applies at rebuild time (an uploaded citation can
    collide with an existing couples/co_cited edge; the deliberate citation
    must not lose to the weaker detector). The engine push reads the table
    back afterwards, so engine and graph_edges always hold the same weight."""
    if not edges:
        return
    db.execute(
        text("INSERT INTO graph_edges (src, dst, weight, context, relation) "
             "VALUES (:src, :dst, :w, :ctx, :rel) "
             "ON CONFLICT (src, dst, context) DO UPDATE SET "
             " weight = GREATEST(graph_edges.weight, EXCLUDED.weight), "
             " relation = CASE WHEN EXCLUDED.weight > graph_edges.weight "
             "   THEN EXCLUDED.relation ELSE graph_edges.relation END"),
        [{"src": e.src, "dst": e.dst, "w": e.weight, "ctx": e.context,
          "rel": e.relation} for e in edges],
    )


# ---------------------------------------------------------------------------
# The confirm itself
# ---------------------------------------------------------------------------

def confirm_upload(db: Session, upload: Upload) -> dict:
    """Apply a reviewed draft. Returns counts for the response. Raises
    ConfirmError with a specific reason on rejection."""
    if upload.status not in ("draft", "engine_pending"):
        raise ConfirmError(f"Upload is {upload.status!r}; nothing to confirm.")

    refs = (db.query(UploadReference)
            .filter(UploadReference.upload_id == upload.id,
                    UploadReference.decision == "accept")
            .order_by(UploadReference.idx).all())
    if not refs:
        raise ConfirmError(
            "No accepted references. Tick at least one entry (DOI/arXiv "
            "matches arrive ticked; everything else needs an explicit tick).")
    if len(refs) > MAX_CONFIRM_REFERENCES:
        raise ConfirmError(
            f"{len(refs)} accepted references exceeds the "
            f"{MAX_CONFIRM_REFERENCES} cap. Reject some entries first.")

    oa = OpenAlex()

    # ---- Postgres transaction: every relational fact, then the version bump.
    own_id = upload.work_id
    n_added = 0
    if own_id is None:
        resolved = (db.get(Work, upload.resolved_work_id)
                    if upload.resolved_work_id else None)
        # Belt over D11: never adopt ANOTHER profile's uploaded local as this
        # upload's own paper, even from a stale draft resolution.
        if resolved is not None and resolved.source == "user_upload":
            owner = db.execute(text(
                "SELECT count(*) FROM uploads WHERE work_id = :w "
                "AND profile_id = :p"), {"w": resolved.id,
                                         "p": upload.profile_id}).scalar_one()
            if not owner:
                resolved = None
        if resolved is not None:
            own_id = resolved.id
        elif upload.resolved_openalex_id:
            own_id = materialise_openalex_work(db, oa, upload.resolved_openalex_id)
            if own_id:
                n_added += 1
        if own_id is None:
            own_id = _local_work(db, upload.title)
            n_added += 1
    upload.work_id = own_id

    ref_work_ids: dict[int, str] = {}
    skipped_unavailable = 0
    for r in refs:
        wid = r.work_id
        if wid is None and r.resolved_openalex_id:
            wid = materialise_openalex_work(db, oa, r.resolved_openalex_id)
            if wid:
                r.work_id = wid
                n_added += 1
            else:
                skipped_unavailable += 1
        if wid:
            ref_work_ids[r.idx] = wid

    if not ref_work_ids:
        db.rollback()
        raise ConfirmError(
            "None of the accepted references could be materialised "
            "(OpenAlex unreachable). Try again later.")

    # citations + denormalised counters. rowcount distinguishes rows this
    # confirm CREATED from pre-existing corpus citations (a corpus paper
    # uploaded by its own author may already carry some) -- undo may only
    # delete what confirm created.
    created_citation: dict[int, bool] = {}
    for r in refs:
        wid = ref_work_ids.get(r.idx)
        if not wid:
            continue
        res = db.execute(text(
            "INSERT INTO citations (src_id, dst_id) VALUES (:s, :d) "
            "ON CONFLICT DO NOTHING"), {"s": own_id, "d": wid})
        created = bool(res.rowcount)
        created_citation[r.idx] = created
        r.created_citation = created
        if created:
            db.execute(text(
                "UPDATE works SET in_corpus_cited_by = in_corpus_cited_by + 1 "
                "WHERE id = :d"), {"d": wid})
    db.execute(text("UPDATE works SET ref_count = :n WHERE id = :w"),
               {"n": len(ref_work_ids), "w": own_id})

    # graph edges: cites/cited_by with the CITED work's epoch factor, plus
    # entity edges for newly materialised works (parity with build_graph.py).
    years = {r[0]: r[1] for r in db.execute(text(
        "SELECT id, year FROM works WHERE id = ANY(:ids)"),
        {"ids": list(ref_work_ids.values())}).all()}
    own_node = work_node(own_id)
    edges: list[Edge] = []
    for wid in ref_work_ids.values():
        f = epoch_factor(years.get(wid))
        edges.append(Edge(own_node, work_node(wid), W["cites"] * f,
                          config.BASELINE_CONTEXT, "cites"))
        edges.append(Edge(work_node(wid), own_node, W["cited_by"] * f,
                          config.BASELINE_CONTEXT, "cited_by"))
    fresh = [w for w in set(ref_work_ids.values()) | {own_id}
             if db.execute(text(
                 "SELECT count(*) FROM graph_edges WHERE src = :n"),
                 {"n": work_node(w)}).scalar_one() == 0]
    for wid in fresh:
        edges.extend(_entity_edges_for(db, wid))
    _persist_edges(db, edges)

    # trust + trust_sources (survivorship: the trust row outlives this upload
    # only through other sources or by having been hand-added -- undo logic).
    profile_id = upload.profile_id
    for r in refs:
        wid = ref_work_ids.get(r.idx)
        if not wid:
            continue
        existing = db.get(Trust, {"profile_id": profile_id, "work_id": wid})
        if existing is None:
            db.add(Trust(profile_id=profile_id, work_id=wid,
                         strength=int(r.strength), is_distrust=False))
            db.flush()
        db.execute(text(
            "INSERT INTO trust_sources (profile_id, work_id, upload_id, "
            " created_trust) VALUES (:p, :w, :u, :c) ON CONFLICT DO NOTHING"),
            {"p": profile_id, "w": wid, "u": upload.id,
             "c": existing is None})

    upload.n_added = n_added
    upload.status = "applying"
    version = bump_graph_version(db)
    db.commit()

    # ---- Engine push, OUTSIDE the transaction: idempotent, reconciled. The
    # edges are read BACK from graph_edges (not the in-memory list), so the
    # engine receives exactly the post-merge weights the table holds.
    committed_edges = _upload_graph_edges(db, upload)
    trust_edges = _trust_edges_for_profile(db, profile_id)
    ok = push_upload_edges(db, committed_edges + trust_edges)
    upload.status = "confirmed" if ok else "engine_pending"
    db.commit()
    if ok:
        # The profile's trust edges just went in with the batch; the next read
        # must not re-put them one by one.
        _mark_profile_seeded(db, profile_id)

    services.invalidate_scores(profile_id)
    log.info("confirm %s: own=%s refs=%d added=%d skipped=%d engine_ok=%s "
             "version=%d", upload.id, own_id, len(ref_work_ids), n_added,
             skipped_unavailable, ok, version)
    return {
        "status": upload.status,
        "work_id": own_id,
        "n_cited": len(ref_work_ids),
        "n_added": n_added,
        "n_skipped_unavailable": skipped_unavailable,
        "n_trust": len(ref_work_ids),
    }


def _mark_profile_seeded(db: Session, profile_id: str) -> None:
    from .models import Profile
    prof = db.get(Profile, profile_id)
    if prof is not None:
        ranking.mark_seeded(db, prof)


def _trust_edges_for_profile(db: Session, profile_id: str) -> list[Edge]:
    """The profile's FULL trust edge set (idempotent to re-put)."""
    ego = profile_node(profile_id)
    out = []
    for t in db.query(Trust).filter(Trust.profile_id == profile_id).all():
        w = (config.DISTRUST_WEIGHT if t.is_distrust
             else config.TRUST_STRENGTH_SCALE.get(t.strength, 0.7))
        out.append(Edge(ego, work_node(t.work_id), w, config.AGGREGATE, "trusts"))
    return out


def push_upload_edges(db: Session, edges: list[Edge]) -> bool:
    """One mr_put_edges batch. True on success. Failure is contained: the
    Postgres truth is already committed and reconciliation repairs the engine."""
    if not edges:
        return True
    try:
        t0 = time.time()
        MeritRank(db.connection()).put_edges(edges)
        db.commit()
        log.info("engine push: %d edges in %.2fs", len(edges), time.time() - t0)
        return True
    except Exception as e:  # noqa: BLE001 - contained by design
        db.rollback()
        log.warning("engine push failed (%d edges): %s", len(edges), str(e)[:200])
        return False


# ---------------------------------------------------------------------------
# Undo (spec): delete this upload's trust_sources; delete each trust row only
# when no other source survives AND this upload created it; delete the
# citations/graph_edges rows the confirm created; one batched mr_delete_edge
# pass (propagates to all contexts per call); bump graph_meta.version. Engine
# node NAMES linger in the registry until restart -- harmless, documented.
# ---------------------------------------------------------------------------

def undo_upload(db: Session, upload: Upload) -> dict:
    profile_id = upload.profile_id
    own_id = upload.work_id
    own_is_local = bool(own_id) and (db.execute(text(
        "SELECT source FROM works WHERE id = :i"), {"i": own_id}
    ).scalar() == "user_upload")

    # 1. Trust survivorship.
    sources = db.execute(text(
        "SELECT work_id, created_trust FROM trust_sources WHERE upload_id = :u"),
        {"u": upload.id}).all()
    db.execute(text("DELETE FROM trust_sources WHERE upload_id = :u"),
               {"u": upload.id})
    n_trust_removed = 0
    for wid, created in sources:
        if not created:
            continue  # hand-added (or another upload created it): survives us
        survivors = db.execute(text(
            "SELECT count(*) FROM trust_sources "
            "WHERE profile_id = :p AND work_id = :w"),
            {"p": profile_id, "w": wid}).scalar_one()
        if survivors == 0:
            db.execute(text(
                "DELETE FROM trust WHERE profile_id = :p AND work_id = :w"),
                {"p": profile_id, "w": wid})
            n_trust_removed += 1

    # 2. Citations + graph edges this confirm created.
    created_refs = db.query(UploadReference).filter(
        UploadReference.upload_id == upload.id,
        UploadReference.created_citation.is_(True),
        UploadReference.work_id.isnot(None)).all() if own_id else []
    edge_pairs: list[tuple[str, str]] = []
    for r in created_refs:
        db.execute(text(
            "DELETE FROM citations WHERE src_id = :s AND dst_id = :d"),
            {"s": own_id, "d": r.work_id})
        db.execute(text(
            "UPDATE works SET in_corpus_cited_by = "
            "greatest(in_corpus_cited_by - 1, 0) WHERE id = :d"),
            {"d": r.work_id})
        edge_pairs.append((work_node(own_id), work_node(r.work_id)))
        edge_pairs.append((work_node(r.work_id), work_node(own_id)))
    if own_is_local:
        # A UL local exists solely because of this upload: every edge touching
        # it goes, and so does the works row itself ("zero residue").
        rows = db.execute(text(
            "SELECT src, dst FROM graph_edges WHERE src = :n OR dst = :n"),
            {"n": work_node(own_id)}).all()
        edge_pairs.extend((r[0], r[1]) for r in rows)
    edge_pairs = list(dict.fromkeys(edge_pairs))
    for src, dst in edge_pairs:
        db.execute(text(
            "DELETE FROM graph_edges WHERE src = :s AND dst = :d"),
            {"s": src, "d": dst})

    # 3. The upload row (CASCADE takes upload_references + any source leftovers)
    #    and, for a local paper, the works row.
    db.delete(upload)
    if own_is_local:
        db.execute(text("DELETE FROM works WHERE id = :i"), {"i": own_id})

    # 4. Trust edges for removed trust rows must leave the engine too.
    removed_trust_edges = [
        (profile_node(profile_id), work_node(wid))
        for wid, created in sources if created
        # (deleted above only when no survivors; re-deriving that set here
        #  would race with the deletes, so recompute from the trust table)
        and db.execute(text(
            "SELECT count(*) FROM trust WHERE profile_id = :p AND work_id = :w"),
            {"p": profile_id, "w": wid}).scalar_one() == 0
    ]

    version = bump_graph_version(db)
    db.commit()

    # 5. One batched engine delete pass, outside the transaction. Each
    #    mr_delete_edge propagates to every context in a single call
    #    (verified, spec B2-method). Failures are tolerable: the next full
    #    rebuild regenerates the engine from the (already-clean) tables.
    mr = MeritRank(db.connection())
    n_engine_deleted = 0
    for src, dst in edge_pairs + removed_trust_edges:
        try:
            mr.delete_edge(src, dst, config.AGGREGATE)
            n_engine_deleted += 1
        except Exception as e:  # noqa: BLE001
            log.warning("undo: mr_delete_edge(%s, %s) failed: %s",
                        src, dst, str(e)[:120])
    db.commit()

    ranking.forget_seeded(profile_id)
    services.invalidate_scores(profile_id)
    log.info("undo %s: %d graph edges, %d trust rows, %d engine deletes, "
             "local=%s version=%d", upload.id, len(edge_pairs),
             n_trust_removed, n_engine_deleted, own_is_local, version)
    return {
        "n_edges_removed": len(edge_pairs),
        "n_trust_removed": n_trust_removed,
        "n_engine_deleted": n_engine_deleted,
        "removed_local_work": own_is_local,
    }


# ---------------------------------------------------------------------------
# Reconciliation: engine_pending uploads are repaired in the background.
# ---------------------------------------------------------------------------

_RECONCILE_INTERVAL = 60.0
_reconcile_started = threading.Event()


def reconcile_pending(db: Session) -> int:
    """Re-push edges for every engine_pending upload. Returns how many were
    repaired. Idempotent: put semantics overwrite identical weights."""
    pending = db.query(Upload).filter(Upload.status == "engine_pending").all()
    repaired = 0
    for upload in pending:
        edges = _upload_graph_edges(db, upload)
        trust_edges = _trust_edges_for_profile(db, upload.profile_id)
        if push_upload_edges(db, edges + trust_edges):
            upload.status = "confirmed"
            db.commit()
            _mark_profile_seeded(db, upload.profile_id)
            services.invalidate_scores(upload.profile_id)
            repaired += 1
    return repaired


def _upload_graph_edges(db: Session, upload: Upload) -> list[Edge]:
    """Recover the upload's edges FROM THE COMMITTED graph_edges ROWS -- the
    derived layer is re-derivable from the layer above it, never recomputed
    from scratch (it might drift).

    Scope: edges touching the uploaded paper's node (that covers every
    cites/cited_by pair, since one endpoint is always the paper) plus edges
    touching works this upload MATERIALISED from OpenAlex (their entity edges
    have no endpoint on the paper). NOT every reference node: the first cut
    swept every edge touching the cited works, and citing eight top-cited
    corpus papers dragged 5,412 pre-existing edges into an 8-reference push.
    Idempotent either way, but 200x the traffic for nothing."""
    if not upload.work_id:
        return []
    own = work_node(upload.work_id)
    nodes = {own}
    for r in db.query(UploadReference).filter(
            UploadReference.upload_id == upload.id,
            UploadReference.work_id.isnot(None),
            UploadReference.resolved_openalex_id.isnot(None)).all():
        nodes.add(work_node(r.work_id))
    rows = db.execute(text(
        "SELECT src, dst, weight, context, relation FROM graph_edges "
        "WHERE src = ANY(:n) OR dst = ANY(:n)"), {"n": list(nodes)}).all()
    return [Edge(r[0], r[1], float(r[2]), r[3], r[4]) for r in rows]


def _sweep_loop() -> None:
    from .db import SessionLocal
    while True:
        time.sleep(_RECONCILE_INTERVAL)
        try:
            with SessionLocal() as db:
                n = reconcile_pending(db)
                if n:
                    log.info("reconcile sweep repaired %d upload(s)", n)
        except Exception:  # noqa: BLE001 - the sweep must survive anything
            log.warning("reconcile sweep failed", exc_info=True)


def start_reconcile_sweep() -> None:
    if _reconcile_started.is_set():
        return
    _reconcile_started.set()
    threading.Thread(target=_sweep_loop, name="upload-reconcile",
                     daemon=True).start()
